version: '3.9'
services:
  db:
    image: mysql:8.0.32-debian
    ports:
      - "${PORT_MAPPING}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - localnet
volumes:
  data:
networks:
  localnet:
    driver: bridge
