version: '3.2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'darkstardb'
    networks:
      - localnet
networks:
  localnet:
    driver: bridge
