version: '3.9'
services:
  db:
    image: mysql:8.0.32-debian
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'darkstardb'
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - localnet
volumes:
  data:
networks:
  localnet:
    driver: bridge
