services:
  db:
    image: mysql:8.0.33-debian
    command: --default-authentication-plugin=mysql_native_password
    cap_add: [ SYS_NICE ]
    ports:
      - "${MYSQL_PORTS}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - mysqlnet

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORTS}"
    networks:
      - mysqlnet

volumes:
  data:
networks:
  mysqlnet:
    driver: bridge
